services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./vols/zk-data:/var/lib/zookeeper/data
      - ./vols/zk-logs:/var/lib/zookeeper/log

  kafka-1:
    image: confluentinc/cp-kafka
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
      KAFKA_BROKER_ID: 1
    volumes:
      - ./vols/kafka-1-data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    expose:
      - '29093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
      KAFKA_BROKER_ID: 2
    volumes:
      - ./vols/kafka-2-data:/var/lib/kafka/data

  kafka-setup:
    image: confluentinc/cp-kafka
    container_name: kafka-setup
    depends_on:
      - kafka-1
      - kafka-2
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Creating kafka topics'

      kafka-topics --bootstrap-server kafka-1:29092 --create --if-not-exists --topic Tweets_Topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-1:29092 --create --if-not-exists --topic News_Topic --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-2:29093 --create --if-not-exists --topic Processed --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics'
      "